### ISSUE TITLE
Assist with dataset.json generation.

### ISSUE THREAD

**Issue by tkkuehn** [khanlab/snakebids#154]
## The problem

Derived BIDS datasets require a `dataset_description.json` with provenance information described under the key `generated_by`. As discussed in today's dev lunch, we should at least provide a way for a Snakebids app to describe itself in the `generated_by` format, and perhaps generate a whole `dataset_description.json`.

Note: this does not preclude any other methods of tracking provenance data, which may be a good idea to be tracked by a separate issue.

**Comment by pvandyken** [comment]
Issue superseded by #221
