### ISSUE TITLE
Extending filtering to meta-data

### ISSUE THREAD

**Issue by Bradley-Karat** [khanlab/snakebids#232]
Discussed the ability of snakebids to handle meta-data from the .json. Believe PyBids already reads meta-data so should be relatively trivial to add functionality to call, index, and manipulate meta-data for all images...

**Comment by tkkuehn** [comment]
Probably too much work for 1.0 but including sidecar JSON filtering would be a useful (optional) feature to include

**Comment by pvandyken** [comment]
AFAIK there's nothing that actually prevents this from working out of the box. Pybids transparently allows metadata fields to be used in `get`, so you should just be able to add these as filters and have it work. If a real-world use cases tries this and encounters problems, we can reopen this discussion, but I'm going to close this in the meantime
