### ISSUE TITLE
Customizable `bids` function based on spec file

### ISSUE THREAD

**Issue by pvandyken** [khanlab/snakebids#245]
The proposal is to implement a new function as follows:

```py
def bids_template(spec: Path | str | BidsPathSpec):
	"""Generate a bids function that constructs files based on the provided spec

	Parameters
	==========
	spec:
		Path to a json or yaml file containing the spec, or a BidsPathSpec shaped dict

	Returns
	=======
	Callable[[<bids args>], str]
```

Then, the existing `bids` function would be implemented as:

```py
bids = bids_template("path/to/default/spec.json")
```

`BidsPathSpec` will dictate the structure of the spec file and will be as follows:

```py
class BidsPathSpec(TypedDict):
	"""Expected structure for spec defining how bids paths shall be constructed
	
	For all entity lists below, the long and short versions of each entity name
	(e.g. "subject" vs "sub") shall be considered synonymous, IF the entity
	is listed in `bids_tags.json` (and possibly in the future, the `pybids` config
	file). Otherwise, the short version of the entity name MUST be used.
	"""

	directories: list[str]
	"""Entities to be used as folders.

	Each entity listed as a directory will be on its own fs level. Each entity may be listed
	AT MOST one time. `datatype` MAY be listed as a directory, but if it is not, it will be
	implicitly included as the last entry in the list. If given, its position in the order
	will be respected.

	Entities listed in `directories` MUST also be listed in `order`, EXCEPT for `datatype`,
	which may not be listed in `order`.
	"""

	order: list[str]
	"""Order of entities in the final path component

	Each entity may be listed AT MOST one time. NONE of `datatype`, `suffix`, `prefix`, and
	`extension` may be listed as entities. `"*"` MAY be listed as an entity, but if it is
	not, it will be implicitly included as the last entry in the list. Either way, its
	position marks the location where unrecognized entities will be inserted. Only entities
	explicitly listed in `order` will be considered "recognized". No information from pybids
	or other sources will be considered.

	All entities must follow the BIDS naming requirements for entity names: only alphanumeric
	characters (regex `r'[a-zA-Z0-9]+'`). `"*"`, the wildcard indicator, is of course the only
	exception.
	"""
```

**Comment by pvandyken** [comment]
@akhanf, @tkkuehn, @kaitj, I'd especially like feedback on the proposal to treat long and short versions of entity names as synonymous. I went this route because our current treatment of names is inconsistent: we use the long versions of `subject` and `session`, but the short versions of everything else. This is extra aggravating because `pybids` always uses the long version, meaning users must give the long version in their `snakebids.yaml` file. I felt the easiest way to tame this without breaking anything was just to allow both. But I'm open to other ideas.

**Comment by pvandyken** [comment]
Obviously, feedback on any other aspect is also welcome, including on the proposed handling of `datatype`.

**Comment by kaitj** [comment]
Just going through the list of issues and realized I missed this. 

re: `subject` / `session` - I think the current implementation came from pybids and I don't know if there was a reason why it strictly uses long-form or these entities. That said, I don't see any downsides to your suggestion of using both long and short forms as long as it is passed properly to the associated entity in pybids as needed.

**Comment by pvandyken** [comment]
By the way, I've been waiting on this issue until we get `bids` moved over to a new repository. I suppose there's nothing stopping us making changes here, but completing the move seemed like a logical first step
