### ISSUE TITLE
Deprecate `participant_label` and `exclude_participant_label` args

### ISSUE THREAD

**Issue by pvandyken** [khanlab/snakebids#262]
Once we finish implementing the filtering apis #241, the `participant_label` and `exclude_participant_label` arguments on `generate_inputs()` become rather redundant. There would, at that point, be three separate ways to filter out subjects: `BidsDatasets.filter()`, the magic `--filter-<component>` args, and the `generate_inputs()` arguments. I think we can probably afford to simplify and deprecate.

**Comment by akhanf** [comment]
If this would also deprecate the --participant_label cli arg, then that would be a deviation from bids-app standards, and it is a quite commonly used option in my experience. We could drop the exclude_participant_label perhaps.

**Comment by pvandyken** [comment]
Ah, no definitely not talking about the cli. I was thinking more the arguments on the generate_inputs function

**Comment by tkkuehn** [comment]
The CLI arg uses this so we should keep it for now, at least until `BidsDataset.filter` exists.

**Comment by pvandyken** [comment]
As implemented in #349, these arguments actually do have distinct features: they apply filtering after paths are found via pybids, meaning you can end up with empty components as opposed to missing components. `--participant-label` also filters before running path parsing, meaning it's faster than running a filter after `generate_inputs`
