### ISSUE TITLE
Use PEP 621-based pyproject.toml in snakebids create

### ISSUE THREAD

**Issue by tkkuehn** [khanlab/snakebids#313]
## The problem

The `setup.py` we create isn't super useful and is setuptools-specific, so we should use something a bit more standard (and incidentally maybe move toward support for hatch) by implementing a pyproject.toml that has the fields defined in PEP 621.

**Comment by kaitj** [comment]
Think this may have been brought up during the initial discussions too and not opposed to moving towards supporting hatch, but this poetry PR is one we should also keep an eye on as they move towards PEP 621. 

https://github.com/python-poetry/poetry-core/pull/567

**Comment by pvandyken** [comment]
This has been resolved by #188
