### ISSUE TITLE
No test dataset in snakebids bootstrap app

### ISSUE THREAD

**Issue by pvandyken** [khanlab/snakebids#347]
`snakebids create` is supposed to drop the tutorial test dataset in the new app, but this doesn't seem to be happening. I don't think the presence of this dataset is actually explicitly tested, which explains how this got past CI.

As of yet, I think the tutorial still says to download the dataset manually, so this issue isn't immediately pressing, but should be fixed as soon as feasible

**Comment by pvandyken** [comment]
Just a note that when I follow the instructions in the `snakebids create` flow, the app doesn't work because the dataset is missing. So this is actually quite serious

**Comment by kaitj** [comment]
I’m out at the moment so maybe i missed something in the code / docs.

It looks like the copier would only copy the project slug if I understand how `run_copy` works in `create`, in addition to those that are conditionally grabbed? Do we need to include the test/data path separately in the copy command?

**Comment by pvandyken** [comment]
Not sure, I'll look into it shortly
