### ISSUE TITLE
Add an option in generate_inputs to ignore files from pybids parsing?

### ISSUE THREAD

**Issue by akhanf** [khanlab/snakebids#381]
## The problem

Would be useful to be able to ignore specific files when parsing a bids dataset.  In my case, it is because I'm now parsing some datasets that include zarr files, folders with a potentially huge number of files, so makes indexing the dataset needlessly inefficient, but was chatting with @pvandyken  about some other potential uses for this (e.g. removing files out of bids spec that are causing conflicts with parsing)..

Turns out that pybids doesn't actually make use of the .bidsignore file, so that option is out. 

Pybids does have an ignore option in their layout indexer that takes a list of strings or regex:
https://bids-standard.github.io/pybids/generated/bids.layout.index.BIDSLayoutIndexer.html#bids.layout.index.BIDSLayoutIndexer

What do you think of simply exposing that parameter in generate_inputs?

**Comment by pvandyken** [comment]
I'm fine with that. AFAIK this would have no effect when using a database, but it at least creates the option.

In principle snakebids could take on the reading of `.bidsignore` itself, but I'd rather punt that down to a potential future integration with rsbids

**Comment by akhanf** [comment]
closing this since the particular use case is fixed now in pybids (ie ignoring .zarr directories)
