### ISSUE TITLE
update tutorial 

### ISSUE THREAD

**Issue by akhanf** [khanlab/snakebids#51]
Created a tutorial in #49, but would be great to fill in any incomplete parts, get new user feedback on the tutorial, and add to it

**Comment by akhanf** [comment]
Comments by @tkkuehn from slack:

I took a look at the tutorial as it is! I don't have a ton of suggestions for things to add other then the spots where there are already TODOs, but here are my thoughts with some minor suggestions:

- The command-line videos are really slick and helpful.
- The structure of the tutorial is generally clear and I appreciate the step-by-step approach.
- Step 1 -- This phrase: “Now, try changing the output smoothing value, e.g. fwhm-10mm, and see what happens. As expected the command still uses a smoothing value of 2.12, since that has been hard-coded, but we will see how to rectify this in the next step.” suggests that the command will actually run, but the video shows it failing because fwhm is not yet a wildcard in the output of the rule.
- Step 5 -- It may be worth describing in what order non-BIDS spec entities are output. A link to the API docs for “bids()” would also do the job, I think.
- Step 5 -- Once we have access to Snakebids, do we still want to be configuring the structure of the input files in the config?
  - Ah I guess this was a lead-in to using “input_path”
- Step 5 -- Formatting of example “bids” invocation has wonky indentation.
- Step 6 -- pprint seems like a very nice module I wasn’t familiar with.
- Step 7 -- Example “input_wildcards” dict has wonky indentation.
    This happens a few other places in Step 7, as well.
- Step 7 -- The explanation of “expand” combining over input_wildcards could use another sentence or two to clarity the expected behaviour.

**Comment by akhanf** [comment]
I think this is something we should prioritize for a 1.0.0 release

**Comment by pvandyken** [comment]
The tutorial has in fact been updated since this issue. I'm going to close for now, since this is out of date
